#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh

if [[ $(xrandr -q | grep 'HDMI-0 connected') ]]; then
	xrandr --output HDMI-0 --primary --mode 3840x2160 --pos 0x0 --rotate normal --output eDP-1-1 --mode 1920x1080 --pos 960x2160 --rotate normal
	xrdb -load $HOME/.config/bspwm/.Xresources.monitor
	bspc monitor HDMI-0 -d I II III IV V VI VII
	bspc monitor eDP-1-1 -d VIII IX X
else
	bspc monitor eDP-1-1 -d I II III IV V VI VII VIII IX X
fi

# autostart programs
kdeconnect-cli &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom -f --config ~/.config/picom.conf --experimental-backends &
~/.fehbg &
wal -R -q & 
fcitx -d &

# remap key
xmodmap -e "keycode 94 = Super_R"

bspc config border_width         2 
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle	 true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
